### ISSUE TITLE
怎么修改插件模板内容，并发布使用插件？

### ISSUE THREAD

**Issue by tigericon** [qq549631030/AndroidJunkCode#11]
我想修改插件的模板 并使用，但是我不知道使用本地插件依赖，可以告诉我该如何操作吗？

**Comment by qq549631030** [comment]
1、修改library下的gradle.properties中的VERSION_NAME，改成比当前最新版本大（比如现在最新的是1.0.7，可以改成1.0.8）
2、修改library下的build.gradle，加上
mavenPublish {
    releaseSigningEnabled = false
}
3、执行library的publishToMavenLocal，1.0.8版本就发布到你的本地了(~/m2/repository)

**Comment by tigericon** [comment]
非常感谢，这个方法是有效的！
