### ISSUE TITLE
关于资源文件替换

### ISSUE THREAD

**Issue by KotlinLan** [qq549631030/AndroidJunkCode#12]
大师你好，请问一下，如何用这个库实现批量替换类名、资源名以及资源图片名称；最简单的就是在原有名称上加前缀或后缀；项目文件太多，如果一个一个refactor-rename的话，太慢了而且工作量很大。谢谢！

**Comment by qq549631030** [comment]
本插件只生成新的垃圾文件，不修改文件的

**Comment by KotlinLan** [comment]
@qq549631030 好的，请问怎么才能把插件源码下载下来，想学习一下呢
