### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Ymmmsick** [qq549631030/AndroidJunkCode#13]
同时打了两个包，一个包正常运行，另外一个包运行报错信息如下：
java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.

看网上的说法是gradle版本过低，但是项目中的版本是gradle-5.4.1-all.zip

**Comment by qq549631030** [comment]
可能是你依赖的某个第三方aar打包时候使用的Android SDK Build Tools版本太低了，想办法更新下这个aar，这是官方的说法
https://developer.android.com/studio/command-line/aapt2#incorrect_configuration_of_libraries

**Comment by Ymmmsick** [comment]
有没有什么办法能查出是哪个依赖使用的build tools版本过低么

**Comment by Ymmmsick** [comment]
这边根据排查发现不是gradle build tools的版本问题了，我们的打包环境是linux+python，在打每一个包之前gradle clean一下，现在没有发现这个问题了
