### ISSUE TITLE
Minimum supported Gradle version is 4.1.

### ISSUE THREAD

**Issue by huyaoqing1995** [qq549631030/AndroidJunkCode#14]
怎么解决Gradle最低版本限制

**Comment by qq549631030** [comment]
你的项目Gradle版本这么低的吗？本插件最低支持到android gradle plugin 3.0.0对应gradle版本4.1，或许你可以考滤下升级项目gradle版本

**Comment by huyaoqing1995** [comment]
> 你的项目Gradle版本这么低的吗？本插件最低支持到android gradle plugin 3.0.0对应gradle版本4.1，或许你可以考滤下升级项目gradle版本

项目中有RN模块，暂时一直没有升级，我下载了源码把library导入到项目里，采用本地插件引用了，但是报这个错，
Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.14.1-all.zip'.
有没有办法降级插件最低版本要求呢？

**Comment by qq549631030** [comment]
1.1.5版本可兼容到AGP1.1.0，gradle应该是2.2.0以上都可以
