### ISSUE TITLE
Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

### ISSUE THREAD

**Issue by Treamz** [qq549631030/AndroidJunkCode#18]
`A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.qq549631030:android-junk-code:1.0.9.
     Required by:
         project :
      > No matching variant of com.github.qq549631030:android-junk-code:1.0.9 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.github.qq549631030:android-junk-code:1.0.9 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'runtimeElements' capability com.github.qq549631030:android-junk-code:1.0.9 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8`

**Comment by qq549631030** [comment]
1.1.0版已修复
