### ISSUE TITLE
未生成垃圾代码

### ISSUE THREAD

**Issue by TokenYc** [qq549631030/AndroidJunkCode#2]
gradle版本6.1.1，按照readme配置后，build apk，在build目录没有看到垃圾代码。

**Comment by qq549631030** [comment]
variant.name 有没有写正确？
如果没有设置productFlavors就是buildType名称（debug，release），如果有设置productFlavors就是flavor+buildType，例如（freeRelease、proRelease）

**Comment by TokenYc** [comment]
多谢了您，确实是这个问题，我刚刚也发现了。
