### ISSUE TITLE
对谷歌审核相似度有用吗？

### ISSUE THREAD

**Issue by jiu20100912** [qq549631030/AndroidJunkCode#22]
生成的类除了类名和方法名，内容基本都一致呀，这样不是更增加了相似度

**Comment by qq549631030** [comment]
主包不要加垃圾代码，马甲包加，这样主包和马甲包就没有什么相似度

**Comment by jiu20100912** [comment]
> 主包不要加垃圾代码，马甲包加，这样主包和马甲包就没有什么相似度

那多个马甲包之间是不就不行了

**Comment by qq549631030** [comment]
多个马甲包的话，每个马甲包basePackage配得不一样，然后生成的各种文件数量也配得不一样就好

**Comment by loohoo** [comment]
可是垃圾代码的逻辑都是一样的行不通吧

**Comment by vae260772** [comment]
> 生成的类除了类名和方法名，内容基本都一致呀，这样不是更增加了相似度

不能直接用，除了名字不同，直接用，号就被封

**Comment by 18319557579** [comment]
这么吓人吗，我正在担心这个问题，用了这个库马甲包之间的逻辑相似度可能还会更高

**Comment by 18319557579** [comment]
> > 生成的类除了类名和方法名，内容基本都一致呀，这样不是更增加了相似度
> 
> 不能直接用，除了名字不同，直接用，号就被封

这么吓人的吗，我正在担心这个问题，用了这个库马甲包之间的逻辑相似度可能还会更高

**Comment by ANewAnonymous** [comment]
> > 生成的类除了类名和方法名，内容基本都一致呀，这样不是更增加了相似度
> 
> 不能直接用，除了名字不同，直接用，号就被封

换一种方法来实现，有兴趣沟通一下

**Comment by mosentest** [comment]
> 可是垃圾代码的逻辑都是一样的行不通吧

你说的没错，作者改下吧，每个方法的逻辑动态改变下吧@ @qq549631030

**Comment by qq549631030** [comment]
1.2.9已经支持完全自定义

**Comment by XiongKe94** [comment]
@mosentest 后面怎么样了
