### ISSUE TITLE
多渠道打包好像无效

### ISSUE THREAD

**Issue by monvyouxi** [qq549631030/AndroidJunkCode#25]

**Comment by qq549631030** [comment]
你的多渠道打包是指？

**Comment by lurendong** [comment]
也许你应该这样打包 productFlavors 名 加 debug 、release 。如你的productFlavor 有 a、b、则 variantConfig {
       aDebug config
        bDebug config
        arelease config
        brelease config
    }

**Comment by monvyouxi** [comment]
感谢，已经知道了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qq549631030/AndroidJunkCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qq549631030/AndroidJunkCode] 多渠道打包好像无效 (Issue #25)





 
也许你应该这样打包 productFlavors 名 加 debug 、release 。如你的productFlavor 有 a、b、则 variantConfig {
 aDebug config
 bDebug config
 arelease config
 brelease config
 }
