### ISSUE TITLE
AndroidManifest  存在placeholder 要怎么处理

### ISSUE THREAD

**Issue by qyf123** [qq549631030/AndroidJunkCode#28]
AndroidManifest  存在 一些三方库的key 占位， 编译时报错， junk manifest 里找不到占位的value ，咨询一下大佬， 这种情况要怎么办呢

**Comment by qq549631030** [comment]
这个应该和junk里生成的AndroidManifest没关系吧，生成的只会合并到最终AndroidManifest里，不会替换任何其它三方库里的东西

**Comment by qyf123** [comment]
您好，邮件已收到。

**Comment by developerzjy** [comment]
> 

您好，我也遇到了这个问题，详细信息提了issue [#30](https://github.com/qq549631030/AndroidJunkCode/issues/30)
