### ISSUE TITLE
设置了多个productFlavors， variantConfig配置flavor+buildType不行

### ISSUE THREAD

**Issue by zhouwenhao** [qq549631030/AndroidJunkCode#29]
设置了多个productFlavors， variantConfig配置flavor+buildType不行。

**Comment by qq549631030** [comment]
你必须写全，比如：比如你的打包命令是assembleFlavor1Flavor2Debug。那你就得配置flavor1Flavor2Debug

**Comment by zhouwenhao** [comment]
androidJunkCode {
        def config = {
            packageBase = "com.xxx.xx"  //生成java类根包名
            packageCount = 30 //生成包数量
            activityCountPerPackage = 3 //每个包下生成Activity类数量
            excludeActivityJavaFile = false //是否排除生成Activity的Java文件,默认false(layout和写入AndroidManifest.xml还会执行)，主要用于处理类似神策全埋点编译过慢问题
            otherCountPerPackage = 50  //每个包下生成其它类的数量
            methodCountPerClass = 20  //每个类下生成方法数量
            resPrefix = "end_"  //生成的layout、drawable、string等资源名前缀
            drawableCount = 300  //生成drawable资源数量
            stringCount = 300  //生成string数量
        }
        variantConfig {
            INDevDebug config //变体名称，如果没有设置productFlavors就是buildType名称，如果有设置productFlavors就是flavor+buildType，例如（freeRelease、proRelease）
            INDevRelease config
        }
    }



INDevDebug和INDevRelease   编译不过报错

**Comment by zhouwenhao** [comment]
如下所示配置，在INDevDebug模式下，打debug包，并未在build/generated/source下看到代码

androidJunkCode {
    def config = {
        packageBase = "com.xxx.xxx"  //生成java类根包名（xxx用来指代实际包名）
        packageCount = 30 //生成包数量
        activityCountPerPackage = 3 //每个包下生成Activity类数量
        excludeActivityJavaFile = false //是否排除生成Activity的Java文件,默认false(layout和写入AndroidManifest.xml还会执行)，主要用于处理类似神策全埋点编译过慢问题
        otherCountPerPackage = 50  //每个包下生成其它类的数量
        methodCountPerClass = 20  //每个类下生成方法数量
        resPrefix = "end_"  //生成的layout、drawable、string等资源名前缀
        drawableCount = 300  //生成drawable资源数量
        stringCount = 300  //生成string数量
    }
    variantConfig {
        iNDevDebug config //变体名称，如果没有设置productFlavors就是buildType名称，如果有设置productFlavors就是flavor+buildType，例如（freeRelease、proRelease）
        iNDevRelease config
    }
}
