### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by TokenYc** [qq549631030/AndroidJunkCode#3]
将com.android.tools.build:gradle:4.0.2升级到com.android.tools.build:gradle:4.1.0
编译时报错：
app\build\generated\source\junk\xxxx\a0\A0Activity.java:17: 错误: 找不到符号setContentView(R.layout.xxxx);

**Comment by qq549631030** [comment]
你升级插件后有没有clean project？

**Comment by TokenYc** [comment]
clean过了，你那边没有问题吗？ @qq549631030

**Comment by qq549631030** [comment]
> clean过了，你那边没有问题吗？ @qq549631030

我这里没有问题，你可能要找找升级gradle插件报错解决方案

**Comment by TokenYc** [comment]
找到原因，并且在demo中复现。
1.com.android.tools.build:gradle:4.1.0
2.distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
3.    dataBinding {
        enabled = true
    }

在开启dataBinding后，clean再build，就会出现找不到符号的问题（实际上是有的） @ @qq549631030

**Comment by qq549631030** [comment]
最新版本1.0.3已解决这个问题
