### ISSUE TITLE
请问不写这条混淆配置会有什么影响吗？

### ISSUE THREAD

**Issue by cheetah747** [qq549631030/AndroidJunkCode#31]
#cn.hx.plugin.ui为前面配置的packageBase
-keep class cn.hx.plugin.ui.** {*;}

**Comment by cheetah747** [comment]
感觉好像不加也行。我们的项目没加这条，刚刚也通过马甲检测了。
而且试了下，加与不加好像编译时间也相同。

**Comment by qq549631030** [comment]
不写的话，如果你开启混淆，生成的文件和方法大部分会被清除，只保留下了生成的Activity类。

**Comment by cheetah747** [comment]
噢噢，原来如此。。
