### ISSUE TITLE
没有正常添加文件呢

### ISSUE THREAD

**Issue by Thanks-xie** [qq549631030/AndroidJunkCode#35]
我按照写的方法，集成到项目后，运行项目没有添加文件进去呢。即使我下载你的项目到本地，运行项目后也是一样，build里面没有任何新增文件呢

**Comment by qq549631030** [comment]
build打包apk，会在app/build/generated/source/junk里

**Comment by GitJoBo** [comment]
你好，你怎么解决的？我这也没有生成，运行demo也没有生成

**Comment by qq549631030** [comment]
Demo只配置了release包才生成，要打release包

**Comment by Thanks-xie** [comment]
你试试看运行demo若是没有生成，就看看打包的模式对不对，还有看看配置里面对应的realse名字有没有对应



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月30日(周三) 下午4:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qq549631030/AndroidJunkCode] 没有正常添加文件呢 (Issue #35)




 
Closed #35 as completed.
