### ISSUE TITLE
api31之后manifest 每一个activity 都需要android:exported 属性 否则将无法编译

### ISSUE THREAD

**Issue by UsingMisz** [qq549631030/AndroidJunkCode#37]
Error:
	android:exported needs to be explicitly specified for element <receiver#com.hyphenate.chat.EMMonitorReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by qq549631030** [comment]
你这个报的是环信sdk里的com.hyphenate.chat.EMMonitorReceiver这个类，本插件生成的Activity没有<intent-filter>所以不用加android:exported
