### ISSUE TITLE
打包有点慢

### ISSUE THREAD

**Issue by zgh10032** [qq549631030/AndroidJunkCode#43]
大佬，我做的马甲包原包69M，想放大1.5倍，到105M，就改配置参数。改大后，首次打包会变的很慢，大约50分钟。gradle.properties的配置我也加了，还有没有别的方法加快打包速度。

**Comment by qq549631030** [comment]
这个主要看方法数，不看包大小，你这加得太多了

**Comment by zgh10032** [comment]
我的配置是这样，配置的不大，达不到要求
             packageCount = 302 //生成包数量
            activityCountPerPackage = 60 //每个包下生成Activity类数量
            excludeActivityJavaFile = true //是否排除生成Activity的Java文件,(layout和写入AndroidManifest.xml还会执行)，主要用于处理类似神策全埋点编译过慢问题
            otherCountPerPackage = 60  //每个包下生成其它类的数量
            methodCountPerClass = 70  //每个类下生成方法数量
            drawableCount = 80  //生成drawable资源数量
            stringCount = 100  //生成string数量52

**Comment by qq549631030** [comment]
刚发布了1.1.7解决了这个问题，你可以试试
