### ISSUE TITLE
没有生成垃圾代码

### ISSUE THREAD

**Issue by lengmo714** [qq549631030/AndroidJunkCode#46]
所有的都是按照说明配置的，但是没有生成垃圾代码啊

**Comment by mosentest** [comment]
+1

**Comment by mosentest** [comment]
> 谢谢您的来信，稍会儿给您回信。

你生成了吗

**Comment by mosentest** [comment]
@qq549631030 按配置，没生成出来

**Comment by qq549631030** [comment]
请提供以下信息：  


**AndroidJunkCode版本**：

**gradle版本**：

**AGP版本**：

**JDK版本**：

**productFlavors配置**：

**androidJunkCode配置**：

**Comment by mosentest** [comment]
> 请提供以下信息：
> 
> **AndroidJunkCode版本**：com.github.qq549631030:android-junk-code:1.2.5
> 
> **gradle版本**：com.android.tools.build:gradle:4.2.2
> 
> **AGP版本**https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
> 
> **JDK版本**：1.8
> 
> **productFlavors配置**：常规的
> 
> **androidJunkCode配置**：androidJunkCode {
    //com.mosen.bikerush.huawei
    def config = {
        packageBase = "com.mosen.xxx.huawei.ui"
        packageCount = 30
        activityCountPerPackage = 3
        excludeActivityJavaFile = false
        otherCountPerPackage = 50
        methodCountPerClass = 20
        resPrefix = "xxx_"
        drawableCount = 300
        stringCount = 300
    }
    variantConfig {
        debug config
        release config
    }
}

**Comment by qq549631030** [comment]
我试了你的配置，用assembleDebug和assembleRelease都可以生成，你查看下app/build/generated/source/junk目录有没有生成文件。

**Comment by DonYeung** [comment]
> Referen

使用assembleDebug和assembleRelease都没有生成app/build/generated/source/junk目录文件

**Comment by mosentest** [comment]
> 我试了你的配置，用assembleDebug和assembleRelease都可以生成，你查看下app/build/generated/source/junk目录有没有生成文件。

没有

**Comment by qq549631030** [comment]
![image](https://github.com/qq549631030/AndroidJunkCode/assets/7122715/2a5921da-29c7-48f2-916d-4f411bee640a)
到 Gradle task 下 app->Tasks->other   里找下有没有这个task

**Comment by mosentest** [comment]
> ![image](https://user-images.githubusercontent.com/7122715/252882680-2a5921da-29c7-48f2-916d-4f411bee640a.png) 到 Gradle task 下 app->Tasks->other 里找下有没有这个task

<img width="365" alt="image" src="https://github.com/qq549631030/AndroidJunkCode/assets/3632260/36a0e77f-1fe8-47c9-b1c7-5e4f50c727df">
没有，老哥

**Comment by qq549631030** [comment]
你这明显是配置了productFlavors呀，有A1,A2呀，配置的时候就不能  
variantConfig {
debug config
release config
}

要用
variantConfig {
a1Debug config
a1Release config
}

**Comment by mosentest** [comment]
> 你这明显是配置了productFlavors呀，有A1,A2呀，配置的时候就不能 variantConfig { debug config release config }
> 
> 要用 variantConfig { a1Debug config a1Release config }

你文档没描述清楚啊

**Comment by qq549631030** [comment]
//变体名称，如果没有设置productFlavors就是buildType名称，如果有设置productFlavors就是flavor+buildType，例如（freeRelease、proRelease）

**Comment by mosentest** [comment]
> //变体名称，如果没有设置productFlavors就是buildType名称，如果有设置productFlavors就是flavor+buildType，例如（freeRelease、proRelease）

def config = {
        def random = new Random()
        packageBase = "com.mosen.bikerush.huawei.ui"
        packageCount = random.nextInt(30) + 15
        activityCountPerPackage = random.nextInt(3) + 1
        excludeActivityJavaFile = false
        otherCountPerPackage = random.nextInt(50) + 25
        methodCountPerClass =  random.nextInt(20) + 10
        resPrefix = "huawei_"
        drawableCount = random.nextInt(300) + 100
        stringCount =  random.nextInt(300) + 100
    }

这样改下行不行

**Comment by mosentest** [comment]
<img width="730" alt="image" src="https://github.com/qq549631030/AndroidJunkCode/assets/3632260/6d5e8a9c-6be9-42ab-ae55-f9849609e3a8">
字符内容，能不能也随机下，不然多个马甲包太类似了

**Comment by mosentest** [comment]
参考这样改写
def lowercase = "abcdefghijklmnopqrstuvwxyz"
def word = new StringBuilder()
def wordLength = random.nextInt(5) + 4
for (int j = 0; j < wordLength; j++) {
word.append(lowercase.charAt(random.nextInt(lowercase.length())))
}

**Comment by qq549631030** [comment]
下个版本把生成方法功能做成可自定义的开放出来

**Comment by mosentest** [comment]
> 下个版本把生成方法功能做成可自定义的开放出来

把activity和other的继承类也放出来吧，这样才能保证类有引用的关系

**Comment by mosentest** [comment]
shrinkResources true  //移出无用资源 
开了这个，清单文件会给抹杀掉

**Comment by qq549631030** [comment]
用1.2.8试试

**Comment by lengmo714** [comment]
谢谢您的来信，稍会儿给您回信。
