### ISSUE TITLE
升到1.1.7 as还是报oom

### ISSUE THREAD

**Issue by qq517103430** [qq549631030/AndroidJunkCode#47]
![image](https://user-images.githubusercontent.com/20501980/211989966-655ec23b-eb18-46ba-b8e2-aec9a65ab390.png)
![image](https://user-images.githubusercontent.com/20501980/211989989-3da25ea3-fea3-4f8e-a512-1b977b756f50.png)
![2ccd5e5bdfde693e6f08085179970ee7](https://user-images.githubusercontent.com/20501980/211990028-a9e11612-88ca-494a-aa6e-40dc82d64986.png)

**Comment by qq549631030** [comment]
你这生成的java类比较多，有200*(80+5) = 17000个，总方法数差不多 17000*60 = 1020000个。你可以试试加大jvm内存
