### ISSUE TITLE
请问多个变体共用一个配置，kotlin应该怎么写？

### ISSUE THREAD

**Issue by jiqianwen** [qq549631030/AndroidJunkCode#48]
![QQ截图20230213141858](https://user-images.githubusercontent.com/26268908/218385016-47f0dfca-6029-46a1-9837-0fa26d60f8cb.png)

**Comment by qq549631030** [comment]
可以像这样：
```kotlin
androidJunkCode {
    val configAction = Action<JunkCodeConfig> {
        packageBase = "cn.hx.plugin.ui"
        packageCount = 30
        activityCountPerPackage = 3
        excludeActivityJavaFile = false
        otherCountPerPackage = 50
        methodCountPerClass = 20
        resPrefix = "junk_"
        drawableCount = 300
        stringCount = 300
    }
    variantConfig {
        create("debug", configAction)
        create("release", configAction)
    }
}
```

**Comment by jiqianwen** [comment]
> 可以像这样：
> 
> ```kotlin
> androidJunkCode {
>     val configAction = Action<JunkCodeConfig> {
>         packageBase = "cn.hx.plugin.ui"
>         packageCount = 30
>         activityCountPerPackage = 3
>         excludeActivityJavaFile = false
>         otherCountPerPackage = 50
>         methodCountPerClass = 20
>         resPrefix = "junk_"
>         drawableCount = 300
>         stringCount = 300
>     }
>     variantConfig {
>         create("debug", configAction)
>         create("release", configAction)
>     }
> }
> ```

好的，感谢
