### ISSUE TITLE
oppo最近好像升级了检测方式，生成了挺多垃圾代码还是检测马甲包

### ISSUE THREAD

**Issue by qq517103430** [qq549631030/AndroidJunkCode#50]
大佬最近有碰到嘛

            packageCount = 200
            activityCountPerPackage = 10
            excludeActivityJavaFile = false
            otherCountPerPackage = 100
            methodCountPerClass = 100

            drawableCount = 500
            stringCount = 500
这是我的配置，生成的垃圾代码很多了
但oppo那边还是显示因您的APP与“xxxx”存在套用马甲的嫌疑（经检测APK相似度0.97155，最高为1），现对您的应用C级上架，请对应用充分自主改动创新，完全跳出模板后再上传；感谢您的支持与配合。如有疑问，可咨询OPPO开放平台客服。

**Comment by qq549631030** [comment]
这么高相似度，你确认下打的包里面是不是真的包括生成的垃圾代码，会不会被混淆去掉了？你是新包上架还是旧包更新？

**Comment by qq517103430** [comment]
好像真是没打进去，旧包更新，刚重新打了一次垃圾代码又打进去了，一直keep住了的 ，不知道上个包为啥没打进去

**Comment by Zorphling** [comment]
> 希望真是没打进去，旧包更新，刚重新打了一次垃圾代码又打进去了，一直住着的，不知道上个包是啥没打进去

请问后面检测结果怎样了？

**Comment by XiongKe94** [comment]
请问后面检测结果怎样了？ @qq517103430
