### ISSUE TITLE
AGP 7.4.2 中生成的代码最终没有打到包里面

### ISSUE THREAD

**Issue by imliujun** [qq549631030/AndroidJunkCode#52]
Android Studio Electric Eel | 2022.1.1 Patch 2
最新版 AndroidStudio，创建一个Android kotlin 新项目，什么都不改，默认为Java JDK 11，AGP 7.4.2，没有开混淆。
接入最新的AndroidJunkCode 1.1.9 版本，代码都生成了，但是最终的 apk 文件中不包含 build/generated/source/junk 中的代码，
资源文件没问题，打到包里面了。

**Comment by qq549631030** [comment]
1.2.0解决了此bug
