### ISSUE TITLE
1.2.0和1.2.12这两个版本没法生成代码

### ISSUE THREAD

**Issue by hjt110** [qq549631030/AndroidJunkCode#53]
1.2.0和1.2.12这两个版本没法生成代码

**Comment by hjt110** [comment]
好吧，是我没加混淆

**Comment by hjt110** [comment]
成功了一次，之后几次没成功了

**Comment by hjt110** [comment]
1.1.7可以用

**Comment by tangligen1995** [comment]
有可能是配置问题，生成垃圾代码的配置是不是要改下

**Comment by qq549631030** [comment]
请提供以下信息：
AndroidJunkCode版本：
gradle版本：
AGP版本：
productFlavors配置：
androidJunkCode配置：

**Comment by chen3441251** [comment]
> > 请提供以下信息： AndroidJunkCode版本： gradle版本： AGP版本： productFlavors配置： androidJunkCode配置：
> 
> 确实只有1.1.7才能生成文件，后面的3个版本都生成的是空文件夹 AndroidJunkCode版本：1.2.1 1.2.3 gradle版本：6.5 AGP版本：4.1.1 productFlavors配置： productFlavors { //配置环境 dev {} prod{} androidJunkCode配置： androidJunkCode { def config = { packageBase = applicationId(包名) + ".xx" packageCount = 20 activityCountPerPackage = 6 excludeActivityJavaFile = false otherCountPerPackage = 40 methodCountPerClass = 20 resPrefix = config_appBuildName + "_" drawableCount = 200 stringCount = 200 } variantConfig { devDebug config devRelease config prodDebug config prodRelease config }

groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.FileWriter(File, sun.nio.cs.UTF_8)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1749)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1556)
	at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:257)

**Comment by chen3441251** [comment]
@qq549631030  1.1.7s 好的  1.1.9就不行了。看改动的话并不多

**Comment by qq549631030** [comment]
是插件用了java11新api问题，不兼容java8，1.2.4已解决

**Comment by chen3441251** [comment]
好的，稍后我在1.2.4验证一下，谢谢大佬



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月09日 09:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [qq549631030/AndroidJunkCode] 1.2.0和1.2.12这两个版本没法生成代码 (Issue #53) |

是插件用了java11新api问题，不兼容java8，1.2.4已解决
