### ISSUE TITLE
生成的xml、java代码所有人都差不多，这不是坑人吗？上架反而增加大量内容重复，导致审核被拒

### ISSUE THREAD

**Issue by vae260772** [qq549631030/AndroidJunkCode#55]
生成的xml全都是textview，代码一样，这不是坑人人吗？反而增加重复量

**Comment by vae260772** [comment]
你java文字里面东西所有人生成的代码都大差不差，用了你的库，反而导致大量重复代码，害人不浅。
你就不能说清楚吗？
矢量xml图片内容，布局文件内容，activity方法内容、其他类方法内容，每个文件名字，如果要保证每个包都不同，需要改你的library库

**Comment by qq549631030** [comment]
生成的java文件名，方法名，内容都是随机的，每个都不一样的，
审核被拒要看你配置生成多少代码，最好生成的垃圾代码是主包代码的0.5倍以上 ，
如果你有更多随机需求可以Fork一份自己实现。

**Comment by vae260772** [comment]
那你使用文档里面说清楚的啊！！！

正常都是远程依赖你的库，谁会去关注生成的内容有没有一致？？？
你文档不说清楚，要使生成的内容不一样，需要自己重写library库，鬼知道啊？？？


你默认写的一套模板，所有人都生成的一样内容，除了名字，查重很容易查出来，害人啊啊！！！！！！！！！！！！

**Comment by ssccbb** [comment]
吹毛求疵了，不符合需求自己下下来改生成逻辑就完了。本来就是同一套代码随机的范围摆在那，公开库哪来的个性定制，这不是拍个脑袋就能想明白的吗

**Comment by lgengsy** [comment]
我看到这个库，想要使用的时候也会考虑这个问题。会不会生成的代码大家都是一样的。如果是一样的那就完蛋了~哈哈
