### ISSUE TITLE
所有的马甲生成xml布局一样，这不是增加重复度吗？？？？

### ISSUE THREAD

**Issue by vae260772** [qq549631030/AndroidJunkCode#56]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <TextView
        android:id="@+id/tv_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center" />
</LinearLayout>

**Comment by qq549631030** [comment]
重复多少是和你的主包对比的，马甲包不管生成什么都是和主包不一样的，而且xml占比很小，大头在生成的java类
