### ISSUE TITLE
用加固的方式，这个插件好像解决不了相似度问题

### ISSUE THREAD

**Issue by usheweb** [qq549631030/AndroidJunkCode#6]
用了插件后再加固后还是会和另外一个用同样加固工具的包相识度过高

**Comment by qq549631030** [comment]
你可以试试两个包生成的类，资源数量不同，把差距弄大点

**Comment by symjdk** [comment]
> 用了插件后再加固后还是会和另外一个用同样加固工具的包相识度过高

您好，方便告诉一下，你们是怎么检测两个包相识度的吗？

**Comment by qq549631030** [comment]
> > 用了插件后再加固后还是会和另外一个用同样加固工具的包相识度过高
> 
> 您好，方便告诉一下，你们是怎么检测两个包相识度的吗？

使用dexcount-gradle-plugin这个插件，可以统计所有的包占比，生成饼图

**Comment by symjdk** [comment]
> > > 用了插件后再加固后还是会和另外一个用同样加固工具的包相识度过高
> > 
> > 
> > 您好，方便告诉一下，你们是怎么检测两个包相识度的吗？
> 
> 使用dexcount-gradle-plugin这个插件，可以统计所有的包占比，生成饼图
好的，谢谢~

**Comment by usheweb** [comment]
问题解决了，是switch (variant.name) 导致的代码不生效。
