### ISSUE TITLE
开启混淆并且加了混淆配置，生成的代码没有打包进去，资源文件是有的

### ISSUE THREAD

**Issue by zhanhon** [qq549631030/AndroidJunkCode#61]
**AndroidJunkCode版本**：1.2.5

**gradle版本**：7.2

**AGP版本**：7.1.2

**JDK版本**：11.0.15

**productFlavors配置**：
buildTypes {
        release {
            minifyEnabled true
            zipAlignEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.relealse
        }
        debug {
            minifyEnabled true
            zipAlignEnabled true
            shrinkResources true
            signingConfig signingConfigs.relealse
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

**androidJunkCode配置**： 
androidJunkCode {
    def config = {
        packageBase = "com.demo.test"  //生成java类根包名
        packageCount = 20 //生成包数量
        activityCountPerPackage = 20 //每个包下生成Activity类数量
        excludeActivityJavaFile = false //是否排除生成Activity的Java文件,默认false(layout和写入AndroidManifest.xml还会执行)，主要用于处理类似神策全埋点编译过慢问题
        otherCountPerPackage = 30  //每个包下生成其它类的数量
        methodCountPerClass = 30  //每个类下生成方法数量
        resPrefix = "test_"  //生成的layout、drawable、string等资源名前缀
        drawableCount = 100  //生成drawable资源数量
        stringCount = 200  //生成string数量
    }
    variantConfig {
        debug config
        release config
    }
}

**bug描述**：
混淆配置
-keep class com.demo.test.** {*;}
开启混淆并且加了混淆配置，生成的代码没有打包进去，资源文件是有的

**Comment by zhanhon** [comment]
![image](https://github.com/qq549631030/AndroidJunkCode/assets/18360628/ee5eca54-9fb5-4d5b-be64-2488a7e8e300)
有生成输出文件

**Comment by qq549631030** [comment]
请确认下  
app/build/outputs/mapping/debug/configuration.txt里有没有包含你的混淆配置  
-keep class com.demo.test.** {*;}

app/build/outputs/mapping/debug/usage.txt里有没有包含生成的垃圾代码：  
com.demo.test.xxxxx

**Comment by zhanhon** [comment]
> 请确认下 app/build/outputs/mapping/debug/configuration.txt里有没有包含你的混淆配置 -keep class com.demo.test.** {*;}
> 
> app/build/outputs/mapping/debug/usage.txt里有没有包含生成的垃圾代码： com.demo.test.xxxxx

现在有了，可能是我之前类生成少了，打包出来查询漏了。谢谢
