### ISSUE TITLE
能开放资源名前缀随机生成吗

### ISSUE THREAD

**Issue by 18319557579** [qq549631030/AndroidJunkCode#63]
填写“resPrefix”后，生成的资源文件前缀名是相同的。现在想要每个资源文件文件名前缀不相同，目前好像做不到，后续打算开放这个然后我们自己实现随机吗

**Comment by qq549631030** [comment]
你可以设置resPrefix为空字符串，这样文件名就不带前缀了

**Comment by 18319557579** [comment]
> 
试了一下的确是可以，但还是更想自己随机文件名，后续如果加这个功能踢我一下呗😜

**Comment by 18319557579** [comment]
开放了drawable、layout、代码随机后，相当好用！啥时候能开放一下string的自定义随机，java代码包名的自定义随机，或者加多一些res随机的类型，例如color、anim，就更棒了

**Comment by qq549631030** [comment]
1.2.9已支持
