### ISSUE TITLE
这个几个能不能给个教程，或者demo里面有简单说明怎么使用，太抽象了

### ISSUE THREAD

**Issue by mosentest** [qq549631030/AndroidJunkCode#65]
//如果不想用插件默认生成的代码，可通过下面实现自定义。注意，修改生成方式后必须先clean再build才生效
        typeGenerator = { typeBuilder ->
            //自定义类实现（类名已经实现随机，Activity类已经实现了onCreate，其它自己实现随机）
            //注意设置了此实现将忽略methodGenerator
            //TypeSpec.Builder用法请参考(https://github.com/square/javapoet)
        }
        methodGenerator = { methodBuilder ->
            //自定义方法实现（方法名已经实现随机，其它自己实现随机）
            //MethodSpec.Builder用法请参考(https://github.com/square/javapoet)
        }
        layoutGenerator = { stringBuilder ->
            //自定义drawable实现（自己实现随机）
        }
        drawableGenerator = { stringBuilder ->
            //自定义layout实现（自己实现随机）
        }

**Comment by 18319557579** [comment]
不抽象啊。你先把博主的源码下载下来，用AS打开，然后去检索你发的这些里面的字符串，你会看到这些功能的使用，然后照猫画虎就行了，我一个小白都看懂了

**Comment by qq549631030** [comment]
已经更新文档
