### ISSUE TITLE
自定义方法实现报错大佬出来指导一下

### ISSUE THREAD

**Issue by chen3441251** [qq549631030/AndroidJunkCode#66]
methodGenerator = { methodBuilder ->
         methodBuilder.addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                        .returns(void.class)
                        .addParameter(String[].class, "args")
                        .addStatement("\$T.out.println(\$S)", System.class, "Hello")
           }

上面的代码写在gradle里面报找不到Modifier.PUBLIC, Modifier.STATIC，请问如何在gradle里面把这个类引进去

**Comment by qq549631030** [comment]
直接import javax.lang.model.element.Modifier
