### ISSUE TITLE
设置productFlavors后未生成预期的冗余代码

### ISSUE THREAD

**Issue by iamlfc** [qq549631030/AndroidJunkCode#67]
首先感谢作者的开源和维护。这边使用的时候遇到一个问题 不设置productFlavors的时候使用正常，设置之后并没有出现预期的效果。我的代码如下：
![dbefea2ceb53861e08f5fb33d1b328d](https://github.com/qq549631030/AndroidJunkCode/assets/19580975/94930842-5ae2-4b5f-82cd-c53b09a55dc3)

![afb010405d029204db7dfdfa88cea77](https://github.com/qq549631030/AndroidJunkCode/assets/19580975/31117655-2409-43d2-b802-e7dd56c79e66)

**Comment by qq549631030** [comment]
首先你只定义了一个维度 style1，但是你在后面 的hwStyle却用了一个没定义的style2 ，所以hwStyle是无效的。

norStyle应该没问题，你的加混淆了没有？

另外提isssue请提供以下信息：

**AndroidJunkCode版本**：

**gradle版本**：

**AGP版本**：

**JDK版本**：

**productFlavors配置**：

**androidJunkCode配置**： 

**bug描述**：

**Comment by iamlfc** [comment]
**AndroidJunkCode版本**： 1.2.8

**gradle版本**： 6.1.1

**AGP版本**：4.0.2

**JDK版本**：11

**productFlavors配置**：如上图

**androidJunkCode配置**： 如上图

**bug描述**：

**Comment by iamlfc** [comment]
没有混淆   hwStyle是为了切换对比的   hwStyle无效是在预料中。但是norStyle确实是没有的  是哪里没配置对吗？

**Comment by qq549631030** [comment]
打开debug看下输出 ：
AndroidJunkCode: generate code for variant ***debug***? ***true***

androidJunkCode {
        debug true  
        ...
}

**Comment by iamlfc** [comment]
这个是日志输出
AndroidJunkCode: generate code for variant hwStyleDebug? true
AndroidJunkCode: generate code for variant hwStyleRelease? true
目前代码生成正常了  没复现上图的那个操作   晚点我再试几次。多谢答复
