### ISSUE TITLE
提示找不到包

### ISSUE THREAD

**Issue by ISSIO** [qq549631030/AndroidJunkCode#68]
**AndroidJunkCode版本**：x.x.x

**gradle版本**：7.0.2

**AGP版本**：7.0.4

**JDK版本**：15

**productFlavors配置**：

**androidJunkCode配置**： 

**bug描述**：sync的时候找不到包
Could not find com.github.qq549631030:android-junk-code:x.x.x.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/qq549631030/android-junk-code/x.x.x/android-junk-code-x.x.x.pom
       - https://jitpack.io/com/github/qq549631030/android-junk-code/x.x.x/android-junk-code-x.x.x.pom
       - https://repo.maven.apache.org/maven2/com/github/qq549631030/android-junk-code/x.x.x/android-junk-code-x.x.x.pom

**Comment by ISSIO** [comment]
大佬请问一下要添加哪个源啊？我这里同步的时候提示找不到包。

**Comment by qq549631030** [comment]
x.x.x 改成 具体的版本号：
com.github.qq549631030:android-junk-code:1.2.9
