### ISSUE TITLE
只生成了activity类, 没有生成其他类, activity类里面没有方法

### ISSUE THREAD

**Issue by shimoat** [qq549631030/AndroidJunkCode#7]

**Comment by qq549631030** [comment]
是开启混淆了吗？可以配置 -dontshrink 关闭压缩

**Comment by chiu14578** [comment]
只要开启了混淆，通过反编译测试，配置了 -dontshrink和shrinkResources false都只生成了activity文件其余文件没生成，activity里面是有方法的，关闭混淆的情况下就正常 @qq549631030

**Comment by qq549631030** [comment]
可以使用 -keep class cn.hx.plugin.ui.** {*;} 来避免。 “cn.hx.plugin.ui”是你配置的packageBase
