### ISSUE TITLE
MethodSpec.methodBuilder 怎么导包呀

### ISSUE THREAD

**Issue by YanRui66** [qq549631030/AndroidJunkCode#72]
**AndroidJunkCode版本**：1.3.2

**gradle版本**：7.1.3

**AGP版本**：

**JDK版本**：11

**productFlavors配置**：

**androidJunkCode配置**： 

**bug描述**：
求助

MethodSpec.methodBuilder 怎么导包呀

**Comment by qq549631030** [comment]
`import com.squareup.javapoet.MethodSpec`  
用的是 [javapoet](https://github.com/square/javapoet)
可参考[JunkUtil](https://github.com/qq549631030/AndroidJunkCode/blob/master/library/src/main/groovy/cn/hx/plugin/junkcode/utils/JunkUtil.groovy)

**Comment by YanRui66** [comment]
okok,感谢感谢
