### ISSUE TITLE
自定义类实现报错

### ISSUE THREAD

**Issue by vip7kk** [qq549631030/AndroidJunkCode#73]
**AndroidJunkCode版本**：1.3.2

**gradle版本**：7.4

**AGP版本**：7.2.2

**JDK版本**：11

**productFlavors配置**：release

**androidJunkCode配置**：            
androidJunkCode {
    variantConfig {
        release {
//注意：这里的release是变体名称，如果没有设置productFlavors就是buildType名称，如果有设置productFlavors就是flavor+buildType，例如（freeRelease、proRelease）
            packageBase = "cn.hx.plugin.ui"  //生成java类根包名
            packageCount = 30 //生成包数量
            activityCountPerPackage = 3 //每个包下生成Activity类数量
            excludeActivityJavaFile = false
            //是否排除生成Activity的Java文件,默认false(layout和写入AndroidManifest.xml还会执行)，主要用于处理类似神策全埋点编译过慢问题
            otherCountPerPackage = 50  //每个包下生成其它类的数量
            methodCountPerClass = 20  //每个类下生成方法数量
            resPrefix = "junk_"  //生成的layout、drawable、string等资源名前缀
            drawableCount = 300  //生成drawable资源数量
            stringCount = 300  //生成string数量

            typeGenerator = { typeBuilder ->
                for (i in 0..<10) {
                    typeBuilder.addMethod(MethodSpec.methodBuilder("a" + i)
                           .addCode("" + "int total = 0;\n" + "for (int i = 0; i < 10; i++) {\n" + "  total += i;\n" + "}\n")
                            .build())
               }
            }
        }
    }
}

**bug描述**：Execution failed for task ':app:generateReleaseJunkCode'.
> No signature of method: cn.hx.plugin.junkcode.ext.JunkCodeConfig.methodBuilder() is applicable for argument types: (String) values: [a0]
![image](https://github.com/qq549631030/AndroidJunkCode/assets/13134448/ac865228-203d-46b0-849e-5a0cae6c742e)

**Comment by qq549631030** [comment]
请提供完整信息

**Comment by qq549631030** [comment]
你没有在build.gradle引入`MethodSpec`
加上这个试试：
`import com.squareup.javapoet.MethodSpec`
