### ISSUE TITLE
打包aab报错

### ISSUE THREAD

**Issue by hdhhdhd** [qq549631030/AndroidJunkCode#74]
**AndroidJunkCode版本**：1.3.2

**gradle版本**：7.5.0

**AGP版本**：7.4.0

**JDK版本**：1.8

**productFlavors配置**：release

**androidJunkCode配置**： 
androidJunkCode {
    def config = {
        packageBase = "tdhdh.zwrtfdhte.dgh.wettq"//生成java类根包名
        packageCount = 30 //生成包数量
        activityCountPerPackage = 3 //每个包下生成Activity类数量
        excludeActivityJavaFile = false
        //是否排除生成Activity的Java文件,默认false(layout和写入AndroidManifest.xml还会执行)，主要用于处理类似神策全埋点编译过慢问题
        otherCountPerPackage = 50  //每个包下生成其它类的数量
        methodCountPerClass = 20  //每个类下生成方法数量
        resPrefix = "fdhdfh_"  //生成的layout、drawable、string等资源名前缀
        drawableCount = 300  //生成drawable资源数量
        stringCount = 300  //生成string数量
    }
    variantConfig {
        //注意：这里的debug,release为变体名称，如果没有设置productFlavors就是buildType名称，如果有设置productFlavors就是flavor+buildType，例如（freeRelease、proRelease）
//        debug config
        release config
    }
}

**bug描述**：打包aab报错
![image](https://github.com/qq549631030/AndroidJunkCode/assets/20127430/5d51d32b-9bc4-40f8-b7c3-cfb8b7ca3376)

**Comment by qq549631030** [comment]
试了下，没有复现这个问题，搜索了下，可能是AGP7.4.0的[bug](https://issuetracker.google.com/issues/261329823)，你可以升级到AGP7.4.2或者更高版本试试

**Comment by hdhhdhd** [comment]
> 试了下，没有复现这个问题，搜索了下，可能是AGP7.4.0的[bug](https://issuetracker.google.com/issues/261329823)，你可以升级到AGP7.4.2或者更高版本试试

确实  升级了就好了
