### ISSUE TITLE
加了垃圾代码后，应用被华为报病毒。 您的应用经检测含有【Android:Evo-gen [Trj]|+AG1442805|egap】病毒

### ISSUE THREAD

**Issue by lostmemoryhp** [qq549631030/AndroidJunkCode#75]
**AndroidJunkCode版本**：
1.3.2
**gradle版本**：
7.3.3
**AGP版本**：
7.2.2
**JDK版本**：
jdk17.0.6
**productFlavors配置**：
   ademo {
            applicationId "com.xx.xxx"
            manifestPlaceholders = [APP_NAME     : "demo",
                                    UMENG_CHANNEL: "huawei"]
        }
**androidJunkCode配置**： 
androidJunkCode {
    def config = {
        android.applicationVariants.all { variant ->
            packageBase = variant.applicationId
        }
        packageCount = 30
        activityCountPerPackage = 30
        excludeActivityJavaFile = false
        otherCountPerPackage = 30
        methodCountPerClass = 30
        resPrefix = "ydxkj_"
        drawableCount = 102
        stringCount = 102
    }
    variantConfig {
        huaweiRelease config
        oppoRelease config
        vivoRelease config
        xiaomiRelease config
        meizuRelease config
        yingyongbaoRelease config
        baiduRelease config
        taobaoRelease config
        c360Release config
    }
}

**bug描述**：
加了垃圾代码后，应用被华为报病毒。 您的应用经检测含有【Android:Evo-gen [Trj]|+AG1442805|egap】病毒

**Comment by qq549631030** [comment]
本插件加的那些垃圾代码都是很简单东西，和病毒应该没关系，这个可能和加固有关。
[使用360加固后 应用被检测出包含病毒【Android:Evo-gen [Trj]|+AG1356486|egap】被拒绝了](https://developer.huawei.com/consumer/cn/forum/topic/0202125250510931151)

**Comment by lostmemoryhp** [comment]
没有加固，我去掉混淆之后就不报病毒了， 也不是所有包都报，很多包都没报，就有一个包报了病毒，是不是可能生成了和病毒类似的名称

**Comment by qq549631030** [comment]
有可能，要是混淆后的名称导致的话，应该不是插件生成的类，因为插件生成的是不会被混淆的。
实现不放心也可以自定义生成类、方法的名称：
classNameCreator，methodNameCreator

**Comment by lostmemoryhp** [comment]
好的
