### ISSUE TITLE
模板的内容也能随机生成就完美了

### ISSUE THREAD

**Issue by wagulu** [qq549631030/AndroidJunkCode#8]
xml的内容和图片单纯的复制多个，内容是完全一样的。

**Comment by qq549631030** [comment]
目前这个插件只是简单的加垃圾代码，应付oppo、vivo应用市场的扫描，它们的扫描功能还没有强大到会比对文件是否相同。目前还没有收到反馈说过不了的，后续如果oppo、vivo的扫描更智能了可以考虑加上。

**Comment by wagulu** [comment]
你好，我想本地定制模板内容，发现拉下来的项目工程使用的是插件，如果使用本地工程中的junklib需要如何配置呢？

**Comment by qq549631030** [comment]
修改library下的project.properties里的project.artifactVersion,比jcenter上的版本大就行，然后执行gradle task   :library:uploadArchives，会编译出新的版本到repo目录下，然后改build.gradle的版本为新版本就可以了
