### ISSUE TITLE
不支持productFlavors首字母大写么？

### ISSUE THREAD

**Issue by ilovexy2tom** [qq549631030/AndroidJunkCode#81]
**AndroidJunkCode版本**：1.3.2

**gradle版本**：7.3.3

**AGP版本**：7.2.1

**JDK版本**：JDK-11

**productFlavors配置**：

```
  c1DeepClean {
          ***
        }
```

**androidJunkCode配置**： 

```
androidJunkCode {
    debug = true
    def config = {
     ***
    }
    variantConfig {
      c1DeepCleanRelease config
    }
}

```

**bug描述**：

首字母换小写就是Ok的，但是

如果我配置以上内容为

`C1DeepCleanRelease config`

渠道也配置为：

```
 C1DeepClean {
          ***
        }
```

AndroidJunkCode: generate code for variant 就一直是false

**Comment by qq549631030** [comment]
AGP里variant name 不管你首字母是大小还是小写都化变成小写
