### ISSUE TITLE
提供是否生成混淆文件的配置

### ISSUE THREAD

**Issue by beilly** [qq549631030/AndroidJunkCode#84]
**AndroidJunkCode版本**：1.3.2

**gradle版本**：8.0

**AGP版本**：8.1.4

**JDK版本**：17

**productFlavors配置**：

**androidJunkCode配置**： 

**bug描述**：生成的垃圾的package 默认都加入keep，可是我想垃圾代码参与混淆。如果需要keep 的话，也希望能自己写 proguard-rules

**Comment by qq549631030** [comment]
1.3.3已支持
[自定义生成proguardFile](https://github.com/qq549631030/AndroidJunkCode/wiki/1.%E8%87%AA%E5%AE%9A%E4%B9%89(%E9%83%A8%E5%88%86)#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%94%9F%E6%88%90proguardfile)
