### ISSUE TITLE
packageCreator 报错 class java.lang.StringBuffer cannot be cast to class java.lang.StringBuilder 

### ISSUE THREAD

**Issue by HolinB** [qq549631030/AndroidJunkCode#90]
**AndroidJunkCode版本**：
1.3.3
**gradle版本**：
8.4
**AGP版本**：
8.3.2
**JDK版本**：
17
**productFlavors配置**：

**androidJunkCode配置**： 

**bug描述**：

![1727333408723](https://github.com/user-attachments/assets/ad79a4f5-1071-495c-ad60-e69f2dd9ffad)

**Comment by qq549631030** [comment]
1.3.4 已修复
