### ISSUE TITLE
AGP 8.3.1  该如何配置？

### ISSUE THREAD

**Issue by peienliudao** [qq549631030/AndroidJunkCode#91]
环境： agp 8.3.1   gradle 8.4-bin在app的build.gradle.kts文件里，添加 release报红
![image](https://github.com/user-attachments/assets/afa2f5c3-522d-4cb3-84cd-c94d74bad9cf)

**Comment by qq549631030** [comment]
![image](https://github.com/user-attachments/assets/9d200cca-185f-4b83-baca-29a9329a8915)

**Comment by peienliudao** [comment]
感谢大佬！
